version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: task_one
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true  # Keep STDIN open for interactive sessions
    tty: true         # Allocate a pseudo-TTY
